DELETE http://localhost:3000/user/deleteUser/8
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsIkVtYWlsIjoidGVzdHN1YmplY3RAZ21haWwuY29tIiwiVXNlclR5cGUiOiJVc2VyIiwiaWF0IjoxNjY4MjY1MTUyfQ
// Only admin can