POST http://localhost:3000/user/register HTTP/1.1
Content-Type: application/json

{
    "FirstName": "Jeremy",
    "LastName" : "Wilkinsss",
    "Email"    : "thomas@hotmail.co.uk",
    "Password" : "passwordlololol",
    "UserType" : "User"
}

// Anyone can register