POST http://localhost:3000/user/register HTTP/1.1
Content-Type: application/json

{
    "FirstName": "testsubjectName",
    "LastName" : "testsubjectsurName",
    "Email"    : "testSubject111@gmail.com",
    "Password" : "passwordtest"
}

// Anyone can register, but the UserType can ONLY be "USER"

POST http://localhost:3000/user/register HTTP/1.1
Content-Type: application/json

{
    "FirstName": "hackerman1234",
    "LastName" : "jackermater",
    "Email"    : "hackerman@gmail.com",
    "Password" : "lolPWNED",
    "UserType" : "Admin"
}

// Here is an example of someone trying to inject "Admin" as usertype, it does not work!