GET http://localhost:3000/product/series/name/Breaking%20Bad


// Anyone can fulfill this request, will be successful

GET http://localhost:3000/product/series/name/Breaking%20Good

// Anyone can fulfill this request, this is meant to fail